central/central.go
cmd/root.go
pkg/badge/badge.go
pkg/badge/badge.svg.tmpl

Changed field name to match shields.io

Fix pkg/badge field names

---

.octocov.yml
cmd/comment.go
config/config.go
config/config_test.go
go.mod
go.sum

If the condition in the `*.acceptable:` section is not met, add an error message to the comment of the pull request.

---

cmd/dump.go
cmd/lsFiles.go

Additional commits to #127

---

Makefile
gh/gh.go
gh/gh_test.go

Fix handling of branch with slash in name

---

.github/workflows/ci.yml
.github/workflows/parallel.yml
cmd/comment.go
gh/gh.go
gh/gh_test.go
report/report.go
testdata/octocov_parallel_tests.yml

ref: #152 
Separate report comments by `repository:` section in .octocov.yml

Separate comment for each repository name

---

.goreleaser/linux.yml

Fix build flags in build for linux

---

.golangci.yml
.octocov.yml
Makefile
cmd/comment.go
cmd/root.go
cmd/summary.go
config/config.go
config/ready.go
config/yaml.go
report/diff_report.go
report/diff_report_test.go
report/report.go
report/report_test.go

https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

Support for adding code metrics report to GitHub Actions Job Summaries

---

config/config.go
config/ready_test.go
gh/gh.go
gh/gh_test.go

Add `is_draft` to https://github.com/k1LoW/octocov#if

Add variable `is_draft`

---

gh/gh.go
gh/gh_test.go

Fix DetectCurrentBranch

---

README.md
gh/gh.go
gh/gh_test.go

Support `GITHUB_PULL_REQUEST_NUMBER` for detecting pull request number

---

cmd/root.go
go.mod
go.sum
report/custom.go
report/report.go
report/report_test.go
testdata/custom_metrics/benchmark_0.json
testdata/custom_metrics/benchmark_1.json

Collect custom metrics

---

report/diff_report.go

fixes https://github.com/k1LoW/octocov/issues/267

swap fileA and fileB results because it was reversed 

---

report/custom.go
report/custom_test.go
testdata/custom_metrics/custom_metric_set_table.3.golden

Swap table XY if custom metrics have many columns.

---

config/ready.go

Make clear the error message of if section

---

datastore/datastore.go

Identify the region of the bucket

---

.github/dependabot.yml
.github/workflows/ci.yml
go.mod

Enable dependabot and update Go version

---

go.mod
go.sum

Update go and pkg version

---

cmd/root.go
config/ready.go

Mitigate conditions for local coverage display.

---

go.mod

Bump up go version

---

.github/workflows/release-test.yml
.github/workflows/tagpr.yml
.goreleaser/darwin.yml
.goreleaser/linux.yml
.goreleaser/windows.yml

Use goreleaser v2

---

cmd/root.go
datastore/local/local.go
ratio/copy_from_gocloc.go
report/report.go
report/report_test.go

Fix lint warn

---

README.md

It seems that latest version is v1.x.
- https://github.com/k1LoW/octocov-action/releases

docs(README): use k1LoW/octocov-action@v1

---

go.mod

chore(deps): update Go version to 1.23.6 in go.mod

---

config/testdata/central_push_enabled_octocov.yml
config/yaml.go
go.mod
go.sum

fix(deps): update goccy/go-yaml

---

.github/workflows/ci.yml
.github/workflows/parallel.yml
.github/workflows/release-test.yml
.github/workflows/tagpr.yml
.pinact.yaml

ci: pin dependencies using pinact

---

datastore/mackerel/mackerel.go
gh/gh.go
report/custom.go
report/diff_report.go
report/report.go

chore: fix lint warn

---

cmd/comment.go
config/config.go
gh/gh.go

It suppose to update existing comment instead of adding new one. So it look more neat and we won't get multiple email notifications while working on pull requests
TODO: write tests
I'd like to hear your thoughts

Add comment.updatePrevious flag

---

config/config.go
config/config_test.go

Fix: #503 
This pull request introduces significant changes to improve precision in calculations for coverage, code-to-test ratio, and test execution time by replacing `float64` with `*big.Rat` (arbitrary-precision rational numbers). It also updates the corresponding test cases to accommodate the new precision-based logic. Below is a summary of the most important changes:
* **Replaced `float64` with `*big.Rat` for calculations**: Updated functions `coverageAcceptable`, `codeToTestRatioAcceptable`, and `testExecutionTimeAcceptable` to use `*big.Rat` instead of `float64` for improved precision in comparisons and calculations. (`config/config.go`, [[1]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L247-R251) …

fix: use big.Rat for precise calculation
