k1LoW/octocov

cmd/view.go
Add an option to specify the path of the coverage report file.
=> Add `--report` option

cmd/diff.go, cmd/view.go, pkg/coverage/coverage.go, pkg/coverage/coverage_test.go, pkg/ratio/ratio.go, pkg/ratio/ratio_test.go, report/report.go, report/report_test.go
```console
$ octocov diff path/to/report_a.json path/to/report_b.json
master (896d3c5)  master (5d1e926)    +/-
--------------------------------------------------------------------
Coverage                        68.5%             38.8%   +29.7%
Files                            31               335     -304
Lines                          2857              6043    -3186
Covered                        1957              2347     -390
Code to Test Ratio              1:0.5             1:0.0     +0.5
Code                           7202            947827  -940625
Test                           3704              2757     +947
Test Execution Time             4m40s                 -   +4m40s
```
```console
$ octocov diff coverage.out path/to/report.json
coverage.out  master (896d3c5)   +/- …
```
=> Add `octocov diff`

cmd/root.go, pkg/coverage/coverage_test.go, report/report.go
```console
$ octocov
octocov version dev
Skip measuring test execution time: env GITHUB_REPOSITORY is not set
out-report (7b042d1)
--------------------------------------------
Coverage                           67.6%
Code to Test Ratio                 1:0.3
Generate coverage report badge...
Generate code-to-test-ratio report badge...
Skip generating badge: test-execution-time is not measured
Commenting report...
Skip commenting the report to pull request: could not get owner and repo
Skip pushing badges: env GITHUB_EVENT_NAME is not set.
```
=> Output code metrics report to STDOUT when octocov command is executed.

central/central.go, cmd/comment.go, cmd/root.go, cmd/view.go, config/config.go, config/config_test.go, datastore/bq/bq.go, pkg/badge/badge.go, pkg/coverage/lcov.go, pkg/ratio/copy_from_gocloc.go, report/report.go
`acceptable:` section can now be used to write conditions.
The variables that can be used are as follows.
| value | description |
| --- | --- |
| `current` | Current code metrics value |
| `prev` | Previous value. This value is taken from `diff.datastores:`. |
| `diff` | The result of `current - prev` |
You can also omit the expression as follows ( code coverage example )
| Omitted expression | Expanded expression |
| --- | --- |
| `60%` | `current >= 60%` |
| `> 60%` | `current > 60%` |
=> Update `acceptable` section logic

README.md, cmd/diff.go, cmd/dump.go, cmd/lsFiles.go, cmd/root.go, cmd/view.go, config/build.go, config/config.go, config/ready.go, config/ready_test.go, report/diff_report_test.go, report/report.go, report/report_test.go
`coverage.path:` -> `coverage.paths:`
=> [BREAKING] Support multiple coverage report files

pkg/coverage/merge.go, pkg/coverage/merge_test.go
Because the coverage counting method will be LOC.
=> When merging coverage reports, if any one of them is not a TypeLOC, it should be TypeMerged.

.goreleaser.yml
ref: #146 
Revert because of problems caused by changing the build environment.
=> Revert build environment

.octocov.yml, README.md, cmd/body.go, cmd/root.go, config/config.go, config/ready.go, config/yaml.go, gh/gh.go, go.mod, go.sum
Support for inserting code metrics report to body of pull request.
|                         | [main](https://github.com/k1LoW/octocov/tree/main) ([39c8672](https://github.com/k1LoW/octocov/commit/39c86726b00af42e6cd0d94430a2c1c5ef8974d7)) | [#172](https://github.com/k1LoW/octocov/pull/172) ([c666757](https://github.com/k1LoW/octocov/commit/c6667577b1be6a25da1beae81b2ad630deb9ad7f)) |  +/-  |
|-------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------:|------------------------------------------------------------------------------------------------------------------------------------------------:|------:|
| **Coverage**            | …
=> Support for inserting code metrics report to body of pull request

README.md, cmd/root.go, config/config.go, gh/gh.go
Currently the commit message is a fixed string, but I made it editable in octocov.yml. This is used when you want to control triggering of ci by commit message.
Examples: [skip ci], [actions skip], etc...
https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
I also noticed that I wasn't getting a message at all if there were no files to commit, so I added that as well. If it's better to split the PR, create a new separate PR
=> feat: customize commit message by octocov.yml

report/report.go
Hi, first of all, thank you for this great tool!
This pull request solves the following error.
```
octocov version 0.47.3
#57[6](https://github.com/[REDACTED]#step:8:7) (51ec1b8)  
---------------------------------------
Coverage                      34.4%  
Code to Test Ratio            1:0.4  
Test Execution Time           1m15s  
Skip commenting report to pull request: comment: is not set
Skip adding report to job summary page: summary: is not set
Inserting report...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc[7](https://github.com/[REDACTED]#step:8:8)0ddc]
goroutine 1 [running]:
github.com/k1LoW/octocov/report.(*Report).CodeToTestRatioRatio(...)
/workdir/report/report.go:374 …
```
=> Fix panic when adding codeToTestRatio for the first time

.octocov.yml, cmd/lsFiles.go, cmd/view.go
=> `octocov ls-files` and `octocov view` should run locally as much as possible.

go.mod, go.sum, pplang/pplang.go
ref: https://github.com/advisories/GHSA-3f2q-6294-fmq5
=> Use github.com/chainguard-dev/git-urls v1.0.2 for fixing https://github.com/advisories/GHSA-3f2q-6294-fmq5

.github/workflows/ci.yml, central/central.go, config/build.go, config/config.go, config/config_test.go, coverage/coverage.go, coverage/coverage_test.go, datastore/datastore.go, datastore/datastore_test.go, datastore/datastore_unix_test.go, datastore/datastore_windows_test.go, internal/path.go, internal/path_test.go, internal/path_unix_test.go, internal/path_windows_test.go, ratio/ratio.go, ratio/ratio_test.go
=> Fix path handling for Windows

coverage/clover.go, coverage/cobertura.go, coverage/coverage.go, coverage/exclude_test.go, coverage/gocover.go, coverage/jacoco.go, coverage/lcov.go, coverage/merge.go, coverage/merge_test.go, coverage/simplecov.go
=> Fix statement type coverage calculation

report/report.go, report/report_test.go
Fix: https://github.com/k1LoW/octocov/issues/387
=> Support wildcard paths in `coverage.paths:`

coverage/merge.go, coverage/merge_test.go
Fix: https://github.com/k1LoW/octocov/issues/394
=> Always count by LOC when merging multiple coverage.

.github/workflows/ci.yml, go.mod
This pull request includes updates to the CI workflow configuration and a minor version update in the `go.mod` file. The most important changes are as follows:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL39-R51): Reordered and updated the `govulncheck` step to use `go-version-file` and `repo-checkout` parameters.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.23.6` to `1.23.7`.
=> ci: update CI workflow and Go version

README.md, cmd/comment.go, cmd/root.go, config/config.go
Hi, octocov is working well on our project. Thank you for great tool.
I wanna propose the setting of `octocov.yaml` to add extra message such as the link of hosted `coverage.html` to code metrics report. Let me know if you have better way.
For instance, we can add the flexible message with environment variable like the following.
```
comment:
message: See [coverage html](${COV_LINK})
```
=> [Feature Reqeust] Add message to code metrics report

.golangci.yml
https://github.com/reviewdog/action-golangci-lint/releases/tag/v2.8.0
[action-golangci](https://github.com/reviewdog/action-golangci-lint) was updated to v2.8.0 3 days ago. That contains migrating to golangci-lint v2, so this repository maybe also need to migrate.
I noticed that when I forked this repo and was trying to run Github Actions.
I just ran `golangci-lint migrate` and pushed the generated yml.
=> migrate .golangci.yml

gh/gh.go, report/diff_report.go
I implemented the feature that is add a status column on diff files report in a pull request.
For now, I simply add `Status` parameter and put it in a table of PR report. If needed, I would be happy to implement this feature as an option, branching based on parameters in `.octocov.yml` file.
=> Add status of diff files on PR report

cmd/comment.go, report/diff_report.go, report/diff_report_test.go
Fix: the bug introduced in #536
This pull request updates the way file coverage tables are generated and displayed, specifically improving how file paths are handled and shown in coverage reports. The changes ensure that file paths are consistently trimmed and cleaned, resulting in more readable links and accurate coverage information. Additionally, the relevant test has been updated to reflect the new method signature.
* Modified the `FileCoveragesTable` method in `report/diff_report.go` to accept the working directory (`wd`) as an argument, allowing for more precise trimming of file path prefixes for better readability.
* Improved file path handling by trimming the working directory prefix from filenames in coverage tables and cleaning up file paths before generating links, resulting in …
=> fix: DiffReport.FileCoveragesTable file name & path

config/build.go
This pull request updates the logic for determining the Git root directory in the `Build()` method of the `Config` struct. Instead of using the `RootPath` function, it now uses the more appropriately named `GitRoot` function from the `internal` package.
Refactoring for clarity and correctness:
* Updated the call in `config/build.go` to use `internal.GitRoot` instead of `internal.RootPath` when setting the `GitRoot` field in the `Config` struct.
=> fix: fix GitRoot in config

.github/workflows/ci.yml, datastore/artifact/artifact.go, gh/gh.go
This pull request updates the artifact storage logic to improve how artifacts are uploaded and managed in GitHub Actions. The main changes involve passing explicit repository and workflow run information to artifact uploads and ensuring old artifacts with the same name are deleted before uploading new ones.
**Artifact upload improvements:**
* The `PutArtifact` method in `gh.go` now requires explicit `owner`, `repo`, and `runID` parameters, and deletes any existing artifact with the same name before uploading the new one. This prevents duplicate artifacts and ensures the latest artifact is always stored.
* The `Put` method in `artifact.go` is updated to parse the repository information and retrieve the `GITHUB_RUN_ID` from the environment, passing these values to `PutArtifact`. This …
=> fix: support artifact re-upload
